module MonographicOrderHelper
  
  def monographic_order_errors_on_rush_order?(monographic_order)
    [:rush_order, :rush_order_reason, :rush_order_reason_other].any?{|field| monographic_order.errors[field].present?}
  end
  
  def monographic_order_errors_on_cataloging_location?(monographic_order)
    [:cataloging_location, :cataloging_location_other].any?{|field| monographic_order.errors[field].present?}
  end
  
  def monographic_selector_options
    Selector.includes(:user).all.sort{|a,b| a.last_first <=> b.last_first}.collect{|s| [s.last_first, s.netid]}
  end
  
  def worldcat_icon
    raw %(<a href="http://www.worldcat.org/" target="_blank"><img border="0" src="https://www.worldcat.org/images/wc_badge_80x15.gif?ai=University_jkennel" width="80" height="15" alt="WorldCat lets people access the collections of libraries worldwide [WorldCat.org]" title="WorldCat lets people access the collections of libraries worldwide [WorldCat.org]"></a>)
  end
  
  def monographic_rush_order_reasons
    RUSH_REASONS
  end
  
  def monographic_formats
    FORMATS
  end
  
  def monographic_collection_codes
    COLLECTION_CODES
  end
  
  def monographic_fund_codes
    FUND_CODES
  end
  
  FORMATS = [
    "Book",
    "DVD",
    "CD",
  ]
  
  RUSH_REASONS = [
    "Needed for class", 
    "Limited availability", 
    "For reserve"
  ]
  
  COLLECTION_CODES = [
    "ARCHT/GEN",
    "ARCHT/REF",
    "AUDIO/CD",
    "AUDIO/DVD",
    "BIC/BICRF",
    "BIC/CARER",
    "BIC/GEN",
    "CHEMP/GEN",
    "CHEMP/REF1",
    "DOCS/HESB",
    "DOCS/REF",
    "ENGIN/GEN",
    "ENGIN/REF",
    "HESB/GEN",
    "HESB/MUS",
    "HESB/STATS",
    "HESB/THREF",
    "KELLO/GEN",
    "KELLO/PEACE",
    "LIBNT/EBRARY",
    "LIFES/NORA",
    "LIFES/OPEN",
    "MATH/GEN",
    "MATH/REF",
    "MATH/STATS",
    "MEDIN/GEN",
    "MICRO/GEN",
    "MRARE/MRARE",
    "REF/GEN",
    "ROME/ARGEN",
    "SPEC/REF",
  ]
  
  FUND_CODES = [
    "ABRA",
    "ACAT",
    "ACMTH",
    "AFST",
    "ALAM",
    "ALAR",
    "ALBEC",
    "ALBEUD",
    "ALBL",
    "ALBLUM",
    "ALCAP",
    "ALCHA",
    "ALCLAU",
    "ALDA",
    "ALDEAK",
    "ALDOS",
    "ALEL",
    "ALFAS",
    "ALFER",
    "ALJEFF",
    "ALKARB",
    "ALKU",
    "ALLASK",
    "ALLY",
    "ALMART",
    "ALMCC",
    "ALMO",
    "ALMONT",
    "ALMOR",
    "ALNOV",
    "ALNRU",
    "ALOD",
    "ALPRIZ",
    "ALRAP",
    "ALROC",
    "ALTHEOREF",
    "ALTOR",
    "ALVASK",
    "AMHIST",
    "AMST",
    "ANTO",
    "ANTY",
    "ARAB",
    "ARCH",
    "ART",
    "BURT",
    "BUSN",
    "BYZA",
    "CATH",
    "CHEM",
    "CHEMENGR",
    "CHPH",
    "CLAC",
    "COMPSCI",
    "DIMA",
    "ECKE",
    "ECON",
    "EDUC",
    "ENGL",
    "FBAF",
    "FCST",
    "FGPO",
    "FILMAPR",
    "FLADGC",
    "FOCA",
    "FOLE",
    "FPROT",
    "FREN",
    "FROST",
    "FRTH",
    "GAMC",
    "GEN",
    "GEND",
    "GERM",
    "GFPO",
    "GOVT",
    "HIST",
    "HPSC",
    "HYFR",
    "IRLIT",
    "JAPN",
    "JOUR",
    "JOYC",
    "KCLASSIC",
    "KPEACEAO",
    "KPEACECD",
    "KPEACEEV",
    "KPEACEJS",
    "KPEACESM",
    "LATNO",
    "LEE",
    "LIBJ",
    "LIPKA",
    "LISC",
    "LSBUSN",
    "LSNI",
    "LSNIDVD",
    "MARY",
    "MATH",
    "MATHC",
    "MBYZ",
    "MEDI",
    "MRUC",
    "MUSC",
    "NGERMAN",
    "OSUL",
    "PCACMST",
    "PCMUSIC",
    "PCPEACE",
    "PEAC",
    "PHDLIT",
    "PHIL",
    "PHYJ",
    "PLAN",
    "PLIB",
    "PSY",
    "RAMHIST",
    "RAMST",
    "RARCH",
    "RBRITLIT",
    "RBUSN",
    "RCHEMPHY",
    "RCOMPSCI",
    "RCSCIENCE",
    "RDUPLIC",
    "RECON",
    "REFE",
    "REFMEDI",
    "RENGLISH",
    "RENGR",
    "RESV",
    "RFILM",
    "RGERM",
    "RHISTCAR",
    "RHLIFESCI",
    "RIRISHLIT",
    "RIRISHST",
    "RITALIAN",
    "RJOURN",
    "RLATAMST",
    "RLIFESCI",
    "RMEDIEVAL",
    "RMUSIC",
    "ROMEARCH",
    "RPDAILL",
    "RPLC",
    "RPORTST",
    "RSCIENCE",
    "RSEE",
    "RSPEC",
    "RSTHEO",
    "RUHIST",
    "RUSN",
    "RYAN",
    "RYNFILM",
    "RYNMUSC",
    "RZEBRA",
    "SCIENGR",
    "SHAN",
    "SHPH",
    "SING",
    "SMIH",
    "SOC",
    "SOCSCI",
    "SPAN",
    "SPGA",
    "STOL",
    "STV",
    "THEO",
    "TRAU",
    "TWIST",
    "ULAST",
    "USHER",
    "WJOU",
  ]
end
