# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

selector_netids = [
  "jarcher",
  "lbayard",
  "tbergstr",
  "bburk1",
  "cszambel",
  "aclemen1",
  "gdannell",
  "ddressin",
  "lfuderer",
  "shayes1",
  "sedwards",
  "ljordan",
  "jkayongo",
  "akrieger",
  "rkusmer",
  "jladwig",
  "nlyandre",
  "cmak",
  "jmatthe2",
  "jmcmanu1",
  "tmiller5",
  "jparker9",
  "gporter",
  "jross",
  "grugg",
  "csmith",
  "fsmith3",
  "msmyth",
  "msteven1",
  "dsulli10",
  "rsimon1"
]

selector_netids.each do |netid|
  if selector = Selector.find_by_netid(netid)
    if !selector.monographic? || !selector.just_say_yes?
      selector.update_attributes!(:monographic => true, :just_say_yes => true)
    end
  else
    selector = Selector.new(:netid => netid, :monographic => true, :just_say_yes => true)
    selector.save!
  end
end

just_say_yes_users = [
  "jarnott",
  "kblackst",
  "ldube",
  "kkinslow",
  "alanghur",
  "plawton",
  "emorgan",
  "lmorgan1",
  "bpietras",
  "crichter",
  "lsharp1",
  "dshorey",
  "ljenny",
  "mvanjaco",
  "dwalker6",
  "nbishop1",
]

just_say_yes_users.each do |netid|
  if selector = Selector.find_by_netid(netid)
    if !selector.just_say_yes?
      selector.update_attributes!(:just_say_yes => true)
    end
  else
    selector = Selector.new(:netid => netid, :just_say_yes => true)
    selector.save!
  end
end

selector_funds = [
  ["jarcher","KPEACEAO"],
  ["jarcher","KPEACECD"],
  ["jarcher","KPEACEEV"],
  ["jarcher","KPEACEJS"],
  ["jarcher","KPEACESM"],
  ["jarcher","KSHAHIN"],
  ["jarcher","PCPEACE"],
  ["jarcher","PCSHARIA"],
  ["jarcher","PEAC"],
  ["jarcher","PEACSO"],
  ["jarcher","SING"],
  ["jarcher","SINGSO"],
  ["Bayard, Laura","ALGO"],
  ["Bayard, Laura","ALMAR"],
  ["Bayard, Laura","ALPO"],
  ["Bayard, Laura","OSUL"],
  ["Bayard, Laura","OSULSO"],
  ["Bayard, Laura","PLIB"],
  ["Bergstrom, Tracy","ALFER"],
  ["Bergstrom, Tracy","ALMO"],
  ["Bergstrom, Tracy","ALMONT"],
  ["Bergstrom, Tracy","COMM"],
  ["Bergstrom, Tracy","ITAL"],
  ["Bergstrom, Tracy","ITALSO"],
  ["Bergstrom, Tracy","RBRNITAL"],
  ["Bergstrom, Tracy","RITALIAN"],
  ["Bergstrom, Tracy","RITALIANSO"],
  ["Bergstrom, Tracy","RLIT"],
  ["Bergstrom, Tracy","RROME"],
  ["Bergstrom, Tracy","RVITALIAN"],
  ["bburk1", "LATNO"],
  ["bburk1", "LATNOS"],
  ["bburk1", "SOC"],
  ["bburk1", "SOCSO"],
  ["bburk1", "SOCS"],
  ["cszambel","CHEMENGR"],
  ["cszambel","COMPSCI"],
  ["cszambel","ECKE"],
  ["cszambel","ENGRSO"],
  ["cszambel","PLAN"],
  ["cszambel","RCOMPSCI"],
  ["cszambel","RENGR"],
  ["Clements, Aedin","ALEL"],
  ["Clements, Aedin","ALNICD"],
  ["Clements, Aedin","ALOC"],
  ["Clements, Aedin","ALRAP"],
  ["Clements, Aedin","CLING"],
  ["Clements, Aedin","HEEK"],
  ["Clements, Aedin","IRLIT"],
  ["Clements, Aedin","IRST"],
  ["Clements, Aedin","RIRISHLIT"],
  ["Clements, Aedin","RIRISHST"],
  ["Clements, Aedin","RIRSHSTSO"],
  ["Clements, Aedin","SMIH"],
  ["Dannelly, Gay","ALBAR"],
  ["Dannelly, Gay","ALCON"],
  ["Dannelly, Gay","ALDEAK"],
  ["Dannelly, Gay","ALFAULK"],
  ["Dannelly, Gay","ALFERN"],
  ["Dannelly, Gay","ALGRE"],
  ["Dannelly, Gay","ALGRIF"],
  ["Dannelly, Gay","ALKR"],
  ["Dannelly, Gay","ALKUN"],
  ["Dannelly, Gay","ALMAC"],
  ["Dannelly, Gay","ALMES"],
  ["Dannelly, Gay","ALPI"],
  ["Dannelly, Gay","ALSEN"],
  ["Dannelly, Gay","BRADG"],
  ["Dannelly, Gay","DIMA"],
  ["Dannelly, Gay","FBDT"],
  ["Dannelly, Gay","FBHI"],
  ["Dannelly, Gay","GEN"],
  ["Dannelly, Gay","GENSO"],
  ["Dannelly, Gay","GRAD"],
  ["Dannelly, Gay","GRADSP"],
  ["Dannelly, Gay","HIST"],
  ["Dannelly, Gay","HISTSO"],
  ["Dannelly, Gay","LGIF"],
  ["Dannelly, Gay","LSDISST"],
  ["Dannelly, Gay","LSGS"],
  ["Dannelly, Gay","LSMI"],
  ["Dannelly, Gay","LSNI"],
  ["Dannelly, Gay","LSNIDVD"],
  ["Dannelly, Gay","MILIS"],
  ["Dannelly, Gay","OGRADY"],
  ["Dannelly, Gay","PCASIAN"],
  ["Dannelly, Gay","PROVG"],
  ["Dannelly, Gay","PROVR"],
  ["Dannelly, Gay","RDUPLIC"],
  ["Dannelly, Gay","RGENLIB"],
  ["Dannelly, Gay","RGENLSO"],
  ["Dannelly, Gay","RHUMAN"],
  ["Dannelly, Gay","RHUMANSO"],
  ["Dannelly, Gay","RPOHSTSO"],
  ["Dannelly, Gay","RPOLHIST"],
  ["Dannelly, Gay","RWLDHIST"],
  ["Dannelly, Gay","RWLDHSTSO"],
  ["Dannelly, Gay","TASS"],
  ["Dannelly, Gay","WEBER"],
  ["Dressing, David","ALAM"],
  ["Dressing, David","ALFE"],
  ["Dressing, David","ALGRAUBART"],
  ["Dressing, David","ALIB"],
  ["Dressing, David","ALMOR"],
  ["Dressing, David","ALPEN"],
  ["Dressing, David","ALVE"],
  ["Dressing, David","ALVIT"],
  ["Dressing, David","COLUM"],
  ["Dressing, David","FLADG"],
  ["Dressing, David","FLADGC"],
  ["Dressing, David","LSKG"],
  ["Dressing, David","PROVLA"],
  ["Dressing, David","RHISTCAR"],
  ["Dressing, David","RLATAMST"],
  ["Dressing, David","RLATSTSO"],
  ["Dressing, David","RPORTST"],
  ["Dressing, David","SPAN"],
  ["Dressing, David","SPANSO"],
  ["Dressing, David","ULAST"],
  ["Dressing, David","WSCONE"],
  ["Fuderer, Laura","ALBR"],
  ["Fuderer, Laura","ALDE"],
  ["Fuderer, Laura","ALDO"],
  ["Fuderer, Laura","ALDUB"],
  ["Fuderer, Laura","ALHAR"],
  ["Fuderer, Laura","ALRI"],
  ["Fuderer, Laura","ALROD"],
  ["Fuderer, Laura","ENGL"],
  ["Fuderer, Laura","ENGLSO"],
  ["Fuderer, Laura","FREN"],
  ["Fuderer, Laura","FRENSO"],
  ["Fuderer, Laura","FRLIT"],
  ["Fuderer, Laura","GFPO"],
  ["Fuderer, Laura","HYFR"],
  ["Fuderer, Laura","HYFRSO"],
  ["Fuderer, Laura","MLIT"],
  ["Fuderer, Laura","PHDLIT"],
  ["Fuderer, Laura","PHDLTSO"],
  ["Fuderer, Laura","RBRITLIT"],
  ["Fuderer, Laura","RBRTLTSO"],
  ["Fuderer, Laura","RENGLISH"],
  ["Fuderer, Laura","RENGLSO"],
  ["Fuderer, Laura","RLFR"],
  ["Fuderer, Laura","USHER"],
  ["Fuderer, Laura","USHERSO"],
  ["Hayes, Steve","ANTO"],
  ["Hayes, Steve","ANTOSO"],
  ["Hayes, Steve","BUSN"],
  ["Hayes, Steve","BUSNSO"],
  ["Hayes, Steve","LSBUSN"],
  ["Hayes, Steve","RBUSN"],
  ["Hayes, Steve","RESBUSN"],
  ["sedwards","FROST"],
  ["sedwards","REFE"],
  ["sedwards","REFESO"],
  ["Jordan, Lou","ALJE"],
  ["Jordan, Lou","ALLIN"],
  ["Jordan, Lou","ALMIR"],
  ["Jordan, Lou","ALSH"],
  ["Jordan, Lou","ARAB"],
  ["Jordan, Lou","ARABG"],
  ["Jordan, Lou","ARBST"],
  ["Jordan, Lou","ASIA"],
  ["Jordan, Lou","CHIN"],
  ["Jordan, Lou","CIVIL"],
  ["Jordan, Lou","COIN"],
  ["Jordan, Lou","DVER"],
  ["Jordan, Lou","GRARE"],
  ["Jordan, Lou","GUO"],
  ["Jordan, Lou","JAPN"],
  ["Jordan, Lou","KASIAN"],
  ["Jordan, Lou","MRARE"],
  ["Jordan, Lou","NDC"],
  ["Jordan, Lou","OGCOIN"],
  ["Jordan, Lou","RARE"],
  ["Jordan, Lou","RARESO"],
  ["Jordan, Lou","RHUMAN2"],
  ["Jordan, Lou","SCOLL"],
  ["Kayongo, Jessica","ALBLUM"],
  ["Kayongo, Jessica","ALKU"],
  ["Kayongo, Jessica","ANTY"],
  ["Kayongo, Jessica","ANTYSO"],
  ["Krieger, Alan","ABRA"],
  ["Krieger, Alan","ABRASO"],
  ["Krieger, Alan","ALCL"],
  ["Krieger, Alan","ALDU"],
  ["Krieger, Alan","ALKARB"],
  ["Krieger, Alan","ALNOV"],
  ["Krieger, Alan","ALOD"],
  ["Krieger, Alan","ALRUS"],
  ["Krieger, Alan","ALSU"],
  ["Krieger, Alan","ALTHEOREF"],
  ["Krieger, Alan","BURT"],
  ["Krieger, Alan","CATH"],
  ["Krieger, Alan","CATHSO"],
  ["Krieger, Alan","CTHEO"],
  ["Krieger, Alan","CTNSG"],
  ["Krieger, Alan","FCST"],
  ["Krieger, Alan","FPROT"],
  ["Krieger, Alan","FPROTSO"],
  ["Krieger, Alan","FRTH"],
  ["Krieger, Alan","GIL"],
  ["Krieger, Alan","MARY"],
  ["Krieger, Alan","PHIL"],
  ["Krieger, Alan","PHILSO"],
  ["Krieger, Alan","RSTHEO"],
  ["Krieger, Alan","SHPH"],
  ["Krieger, Alan","THEO"],
  ["Krieger, Alan","THEOSO"],
  ["Krieger, Alan","TRAU"],
  ["Kusmer, Rob","ALBOES"],
  ["Kusmer, Rob","ALHO"],
  ["Kusmer, Rob","ALROC"],
  ["Kusmer, Rob","GERM"],
  ["Kusmer, Rob","GERMSO"],
  ["Kusmer, Rob","NGERMAN"],
  ["Kusmer, Rob","PHDLIT"],
  ["Kusmer, Rob","PHDLTSO"],
  ["Kusmer, Rob","RGERM"],
  ["Kusmer, Rob","RGERMSO"],
  ["jladwig","ECON"],
  ["jladwig","ECONSO"],
  ["jladwig","LEE"],
  ["jladwig","LISC"],
  ["jladwig","LISCSO"],
  ["jladwig","MATH"],
  ["jladwig","MATHC"],
  ["jladwig","MATHSO"],
  ["jladwig","PCACMST"],
  ["jladwig","PCAMSTSO"],
  ["jladwig","RASCIENGR1"],
  ["jladwig","RASCIENGR2"],
  ["jladwig","RCSCIENCE"],
  ["jladwig","RECON"],
  ["jladwig","RECONSO"],
  ["jladwig","RHLIFESCI"],
  ["jladwig","RLIFESCI"],
  ["jladwig","RSCIENCE"],
  ["jladwig","RSCISO"],
  ["jladwig","RZEBRA"],
  ["jladwig","SCIENGR"],
  ["jladwig","STOL"],
  ["Lyandres, Natasha","ALDA"],
  ["Lyandres, Natasha","ALMART"],
  ["Lyandres, Natasha","ALNRU"],
  ["Lyandres, Natasha","LSNI"],
  ["Lyandres, Natasha","LSNIDVD"],
  ["Lyandres, Natasha","LSNIGILL"],
  ["Lyandres, Natasha","MRUC"],
  ["Lyandres, Natasha","MRUCSO"],
  ["Lyandres, Natasha","PCPDA"],
  ["Lyandres, Natasha","RSEE"],
  ["Lyandres, Natasha","RUHIST"],
  ["Lyandres, Natasha","RUSHIST"],
  ["Lyandres, Natasha","RUSN"],
  ["Lyandres, Natasha","RUSNSO"],
  ["Mak, Collette","RESV"],
  ["Mak, Collette","RILLFAC"],
  ["Mak, Collette","RPDAILL"],
  ["Matthews, Jennifer","ALAR"],
  ["Matthews, Jennifer","ALBEC"],
  ["Matthews, Jennifer","ALBEUD"],
  ["Matthews, Jennifer","ALFAS"],
  ["Matthews, Jennifer","ALJEFF"],
  ["Matthews, Jennifer","ALPRIZ"],
  ["Matthews, Jennifer","FILM"],
  ["Matthews, Jennifer","FILMAPR"],
  ["Matthews, Jennifer","LIBJ"],
  ["Matthews, Jennifer","LIBJSO"],
  ["Matthews, Jennifer","MUSC"],
  ["Matthews, Jennifer","PCMUSIC"],
  ["Matthews, Jennifer","RFILM"],
  ["Matthews, Jennifer","RFILMSO"],
  ["Matthews, Jennifer","RMISMUSC"],
  ["Matthews, Jennifer","RMUSCSO"],
  ["Matthews, Jennifer","RMUSIC"],
  ["Matthews, Jennifer","RSMUSIC"],
  ["Matthews, Jennifer","RYNFILM"],
  ["Matthews, Jennifer","RYNMUSC"],
  ["Matthews, Jennifer","RYNMUSCSO"],
  ["McManus, Jean","ACAT"],
  ["McManus, Jean","FOCA"],
  ["McManus, Jean","GAMC"],
  ["Miller, Thurston","CHEM"],
  ["Miller, Thurston","CHPHSO"],
  ["Miller, Thurston","PCSPECTRA"],
  ["Miller, Thurston","PHYJ"],
  ["Miller, Thurston","RACHSO"],
  ["Miller, Thurston","RCHEMPHY"],
  ["Miller, Thurston","RCSCIENCE"],
  ["Miller, Thurston","RSCIENCE"],
  ["Miller, Thurston","RSCISO"],
  ["Miller, Thurston","SCIENGR2"],
  ["Parker, Jennifer","ARCH"],
  ["Parker, Jennifer","LSARCH"],
  ["Parker, Jennifer","RARCH"],
  ["Parker, Jennifer","RARCHSO"],
  ["Parker, Jennifer","ROMEARCH"],
  ["gporter","AFST"],
  ["gporter","ALDOS"],
  ["gporter","ALMC"],
  ["gporter","ALWI"],
  ["gporter","AMHIST"],
  ["gporter","AMST"],
  ["gporter","FBAF"],
  ["gporter","FOLE"],
  ["gporter","GEND"],
  ["gporter","JOUR"],
  ["gporter","PROVAF"],
  ["gporter","RAMHIST"],
  ["gporter","RAMST"],
  ["gporter","RJOURN"],
  ["gporter","RSCHMAMST"],
  ["gporter","TWIST"],
  ["gporter","WJOU"],
  ["Ross, Joe","HPSC"],
  ["Ross, Joe","HPSCSO"],
  ["Ross, Joe","STV"],
  ["Rugg, George","JOYC"],
  ["Rugg, George","OGCIV"],
  ["Rugg, George","SPGA"],
  ["ljenny","LIBTS"],
  ["ljenny","LIBTSO"],
  ["ljenny","RPLC"],
  ["Smith, Cheri","ALCAP"],
  ["Smith, Cheri","ALCLAU"],
  ["Smith, Cheri","ALHU"],
  ["Smith, Cheri","ALKE"],
  ["Smith, Cheri","ALLASK"],
  ["Smith, Cheri","ALVASK"],
  ["Smith, Cheri","EDUC"],
  ["Smith, Cheri","GOVT"],
  ["Smith, Cheri","GOVTSO"],
  ["Smith, Cheri","PSY"],
  ["Smith, Cheri","SOCSCI"],
  ["Smith, Felicia","ALRODM"],
  ["Smith, Felicia","LATNO"],
  ["Smith, Felicia","SOC"],
  ["Smith, Felicia","SOCSO"],
  ["Smyth, Marina","MEDI"],
  ["Smyth, Marina","MEDISO"],
  ["Smyth, Marina","REFMEDI"],
  ["Smyth, Marina","RMEDIEVAL"],
  ["Smyth, Marina","RMEDISO"],
  ["Smyth, Marina","SHAN"],
  ["Stevenson, Marsha","ALGOPI"],
  ["Stevenson, Marsha","ALRH"],
  ["Stevenson, Marsha","ART"],
  ["Stevenson, Marsha","INFDVD"],
  ["Stevenson, Marsha","LIPKA"],
  ["Stevenson, Marsha","RSPEC"],
  ["Stevenson, Marsha","RYAN"],
  ["Stevenson, Marsha","RYANSO"],
  ["dsulli10","ALBL"],
  ["dsulli10","ALBRA"],
  ["dsulli10","ALFO"],
  ["dsulli10","ALHERN"],
  ["dsulli10","ALMULL"],
  ["dsulli10","ALSC"],
  ["dsulli10","ALTHO"],
  ["dsulli10","ALTOR"],
  ["dsulli10","ANAST"],
  ["dsulli10","BYZA"],
  ["dsulli10","CLAC"],
  ["dsulli10","CLACSO"],
  ["dsulli10","FRHI"],
  ["dsulli10","KCLASSIC"],
  ["dsulli10","MBYZ"],
  ["dsulli10","MBYZSO"],
  ["dsulli10","VACCA"],
  ["rsimon1","ALBEUD"],
  ["rsimon1","ALJEFF"],
  ["rsimon1","MAPR"],
  ["rsimon1","MUSC"],
  ["rsimon1","PCMUSIC"],
  ["rsimon1","RMISMUSC"],
  ["rsimon1","RMUSIC"],
  ["rsimon1","ROPEERAPR"],
  ["rsimon1","RSMUSIC"],
]

selector_funds.each do |selector_name, fund_name|
  user = User.guess_by_name(selector_name)
  if SelectorFund.where(:netid => user.netid, :name => fund_name).count == 0
    SelectorFund.create(:netid => user.netid, :name => fund_name)
  end
end