require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Directory::AdministrativeUsersController do

  # This should return the minimal set of attributes required to create a valid
  # Directory::AdministrativeUser. As you add validations to Directory::AdministrativeUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Directory::AdministrativeUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all directory_administrative_users as @directory_administrative_users" do
      administrative_user = Directory::AdministrativeUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directory_administrative_users).should eq([administrative_user])
    end
  end

  describe "GET show" do
    it "assigns the requested directory_administrative_user as @directory_administrative_user" do
      administrative_user = Directory::AdministrativeUser.create! valid_attributes
      get :show, {:id => administrative_user.to_param}, valid_session
      assigns(:directory_administrative_user).should eq(administrative_user)
    end
  end

  describe "GET new" do
    it "assigns a new directory_administrative_user as @directory_administrative_user" do
      get :new, {}, valid_session
      assigns(:directory_administrative_user).should be_a_new(Directory::AdministrativeUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested directory_administrative_user as @directory_administrative_user" do
      administrative_user = Directory::AdministrativeUser.create! valid_attributes
      get :edit, {:id => administrative_user.to_param}, valid_session
      assigns(:directory_administrative_user).should eq(administrative_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Directory::AdministrativeUser" do
        expect {
          post :create, {:directory_administrative_user => valid_attributes}, valid_session
        }.to change(Directory::AdministrativeUser, :count).by(1)
      end

      it "assigns a newly created directory_administrative_user as @directory_administrative_user" do
        post :create, {:directory_administrative_user => valid_attributes}, valid_session
        assigns(:directory_administrative_user).should be_a(Directory::AdministrativeUser)
        assigns(:directory_administrative_user).should be_persisted
      end

      it "redirects to the created directory_administrative_user" do
        post :create, {:directory_administrative_user => valid_attributes}, valid_session
        response.should redirect_to(Directory::AdministrativeUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directory_administrative_user as @directory_administrative_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::AdministrativeUser.any_instance.stub(:save).and_return(false)
        post :create, {:directory_administrative_user => {  }}, valid_session
        assigns(:directory_administrative_user).should be_a_new(Directory::AdministrativeUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::AdministrativeUser.any_instance.stub(:save).and_return(false)
        post :create, {:directory_administrative_user => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directory_administrative_user" do
        administrative_user = Directory::AdministrativeUser.create! valid_attributes
        # Assuming there are no other directory_administrative_users in the database, this
        # specifies that the Directory::AdministrativeUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Directory::AdministrativeUser.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => administrative_user.to_param, :directory_administrative_user => { "these" => "params" }}, valid_session
      end

      it "assigns the requested directory_administrative_user as @directory_administrative_user" do
        administrative_user = Directory::AdministrativeUser.create! valid_attributes
        put :update, {:id => administrative_user.to_param, :directory_administrative_user => valid_attributes}, valid_session
        assigns(:directory_administrative_user).should eq(administrative_user)
      end

      it "redirects to the directory_administrative_user" do
        administrative_user = Directory::AdministrativeUser.create! valid_attributes
        put :update, {:id => administrative_user.to_param, :directory_administrative_user => valid_attributes}, valid_session
        response.should redirect_to(administrative_user)
      end
    end

    describe "with invalid params" do
      it "assigns the directory_administrative_user as @directory_administrative_user" do
        administrative_user = Directory::AdministrativeUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::AdministrativeUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => administrative_user.to_param, :directory_administrative_user => {  }}, valid_session
        assigns(:directory_administrative_user).should eq(administrative_user)
      end

      it "re-renders the 'edit' template" do
        administrative_user = Directory::AdministrativeUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::AdministrativeUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => administrative_user.to_param, :directory_administrative_user => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directory_administrative_user" do
      administrative_user = Directory::AdministrativeUser.create! valid_attributes
      expect {
        delete :destroy, {:id => administrative_user.to_param}, valid_session
      }.to change(Directory::AdministrativeUser, :count).by(-1)
    end

    it "redirects to the directory_administrative_users list" do
      administrative_user = Directory::AdministrativeUser.create! valid_attributes
      delete :destroy, {:id => administrative_user.to_param}, valid_session
      response.should redirect_to(directory_administrative_users_url)
    end
  end

end
