require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Directory::ContactInformationsController do

  # This should return the minimal set of attributes required to create a valid
  # Directory::ContactInformation. As you add validations to Directory::ContactInformation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { contact_information: "332-3323" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Directory::ContactInformationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all directory_contact_informations as @directory_contact_informations" do
      contact_information = Directory::ContactPhone.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directory_contact_informations).should eq([contact_information])
    end
  end

  describe "GET show" do
    it "assigns the requested directory_contact_information as @directory_contact_information" do
      contact_information = Directory::ContactPhone.create! valid_attributes
      get :show, {:id => contact_information.to_param}, valid_session
      assigns(:directory_contact_information).should eq(contact_information)
    end
  end

  describe "GET new" do
    it "assigns a new directory_contact_information as @directory_contact_information" do
      get :new, {}, valid_session
      assigns(:directory_contact_information).should be_a_new(Directory::ContactInformation)
    end
  end

  describe "GET edit" do
    it "assigns the requested directory_contact_information as @directory_contact_information" do
      contact_information = Directory::ContactPhone.create! valid_attributes
      get :edit, {:id => contact_information.to_param}, valid_session
      assigns(:directory_contact_information).should eq(contact_information)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Directory::ContactInformation" do
        expect {
          post :create, {:directory_contact_information => valid_attributes}, valid_session
        }.to change(Directory::ContactInformation, :count).by(1)
      end

      it "assigns a newly created directory_contact_information as @directory_contact_information" do
        post :create, {:directory_contact_information => valid_attributes}, valid_session
        assigns(:directory_contact_information).should be_a(Directory::ContactInformation)
        assigns(:directory_contact_information).should be_persisted
      end

      it "redirects to the created directory_contact_information" do
        post :create, {:directory_contact_information => valid_attributes}, valid_session
        response.should redirect_to(Directory::ContactInformation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directory_contact_information as @directory_contact_information" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::ContactInformation.any_instance.stub(:save).and_return(false)
        post :create, {:directory_contact_information => {  }}, valid_session
        assigns(:directory_contact_information).should be_a_new(Directory::ContactInformation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::ContactPhone.any_instance.stub(:save).and_return(false)
        post :create, {:directory_contact_information => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directory_contact_information" do
        contact_information = Directory::ContactPhone.create! valid_attributes
        # Assuming there are no other directory_contact_informations in the database, this
        # specifies that the Directory::ContactInformation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Directory::ContactPhone.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => contact_information.to_param, :directory_contact_information => { "these" => "params" }}, valid_session
      end

      it "assigns the requested directory_contact_information as @directory_contact_information" do
        contact_information = Directory::ContactInformation.create! valid_attributes
        put :update, {:id => contact_information.to_param, :directory_contact_information => valid_attributes}, valid_session
        assigns(:directory_contact_information).should eq(contact_information)
      end

      it "redirects to the directory_contact_information" do
        contact_information = Directory::ContactInformation.create! valid_attributes
        put :update, {:id => contact_information.to_param, :directory_contact_information => valid_attributes}, valid_session
        response.should redirect_to(contact_information)
      end
    end

    describe "with invalid params" do
      it "assigns the directory_contact_information as @directory_contact_information" do
        contact_information = Directory::ContactPhone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::ContactPhone.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_information.to_param, :directory_contact_information => {  }}, valid_session
        assigns(:directory_contact_information).should eq(contact_information)
      end

      it "re-renders the 'edit' template" do
        contact_information = Directory::ContactPhone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::ContactPhone.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_information.to_param, :directory_contact_information => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directory_contact_information" do
      contact_information = Directory::ContactPhone.create! valid_attributes
      expect {
        delete :destroy, {:id => contact_information.to_param}, valid_session
      }.to change(Directory::ContactPhone, :count).by(-1)
    end

    it "redirects to the directory_contact_informations list" do
      contact_information = Directory::ContactPhone.create! valid_attributes
      delete :destroy, {:id => contact_information.to_param}, valid_session
      response.should redirect_to(directory_contact_informations_url)
    end
  end

end
