require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Directory::EmployeeUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # Directory::EmployeeUnit. As you add validations to Directory::EmployeeUnit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { employee_id: "1", organizational_unit_id: "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Directory::EmployeeUnitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all directory_employee_units as @directory_employee_units" do
      employee_unit = Directory::EmployeeUnit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directory_employee_units).should eq([employee_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested directory_employee_unit as @directory_employee_unit" do
      employee_unit = Directory::EmployeeUnit.create! valid_attributes
      get :show, {:id => employee_unit.to_param}, valid_session
      assigns(:directory_employee_unit).should eq(employee_unit)
    end
  end

  describe "GET new" do
    it "assigns a new directory_employee_unit as @directory_employee_unit" do
      get :new, {}, valid_session
      assigns(:directory_employee_unit).should be_a_new(Directory::EmployeeUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested directory_employee_unit as @directory_employee_unit" do
      employee_unit = Directory::EmployeeUnit.create! valid_attributes
      get :edit, {:id => employee_unit.to_param}, valid_session
      assigns(:directory_employee_unit).should eq(employee_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Directory::EmployeeUnit" do
        expect {
          post :create, {:directory_employee_unit => valid_attributes}, valid_session
        }.to change(Directory::EmployeeUnit, :count).by(1)
      end

      it "assigns a newly created directory_employee_unit as @directory_employee_unit" do
        post :create, {:directory_employee_unit => valid_attributes}, valid_session
        assigns(:directory_employee_unit).should be_a(Directory::EmployeeUnit)
        assigns(:directory_employee_unit).should be_persisted
      end

      it "redirects to the created directory_employee_unit" do
        post :create, {:directory_employee_unit => valid_attributes}, valid_session
        response.should redirect_to(Directory::EmployeeUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directory_employee_unit as @directory_employee_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::EmployeeUnit.any_instance.stub(:save).and_return(false)
        post :create, {:directory_employee_unit => {  }}, valid_session
        assigns(:directory_employee_unit).should be_a_new(Directory::EmployeeUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::EmployeeUnit.any_instance.stub(:save).and_return(false)
        post :create, {:directory_employee_unit => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directory_employee_unit" do
        employee_unit = Directory::EmployeeUnit.create! valid_attributes
        # Assuming there are no other directory_employee_units in the database, this
        # specifies that the Directory::EmployeeUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Directory::EmployeeUnit.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => employee_unit.to_param, :directory_employee_unit => { "these" => "params" }}, valid_session
      end

      it "assigns the requested directory_employee_unit as @directory_employee_unit" do
        employee_unit = Directory::EmployeeUnit.create! valid_attributes
        put :update, {:id => employee_unit.to_param, :directory_employee_unit => valid_attributes}, valid_session
        assigns(:directory_employee_unit).should eq(employee_unit)
      end

      it "redirects to the directory_employee_unit" do
        employee_unit = Directory::EmployeeUnit.create! valid_attributes
        put :update, {:id => employee_unit.to_param, :directory_employee_unit => valid_attributes}, valid_session
        response.should redirect_to(employee_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the directory_employee_unit as @directory_employee_unit" do
        employee_unit = Directory::EmployeeUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::EmployeeUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_unit.to_param, :directory_employee_unit => {  }}, valid_session
        assigns(:directory_employee_unit).should eq(employee_unit)
      end

      it "re-renders the 'edit' template" do
        employee_unit = Directory::EmployeeUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::EmployeeUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee_unit.to_param, :directory_employee_unit => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directory_employee_unit" do
      employee_unit = Directory::EmployeeUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => employee_unit.to_param}, valid_session
      }.to change(Directory::EmployeeUnit, :count).by(-1)
    end

    it "redirects to the directory_employee_units list" do
      employee_unit = Directory::EmployeeUnit.create! valid_attributes
      delete :destroy, {:id => employee_unit.to_param}, valid_session
      response.should redirect_to(directory_employee_units_url)
    end
  end

end
