require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Directory::EmployeesController do

  # This should return the minimal set of attributes required to create a valid
  # Directory::Employee. As you add validations to Directory::Employee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { netid: "ffffff3" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Directory::EmployeesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all directory_employees as @directory_employees" do
      employee = Directory::Employee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:directory_employees).should eq([employee])
    end
  end

  describe "GET show" do
    it "assigns the requested directory_employee as @directory_employee" do
      employee = Directory::Employee.create! valid_attributes
      get :show, {:id => employee.to_param}, valid_session
      assigns(:directory_employee).should eq(employee)
    end
  end

  describe "GET new" do
    it "assigns a new directory_employee as @directory_employee" do
      get :new, {}, valid_session
      assigns(:directory_employee).should be_a_new(Directory::Employee)
    end
  end

  describe "GET edit" do
    it "assigns the requested directory_employee as @directory_employee" do
      employee = Directory::Employee.create! valid_attributes
      get :edit, {:id => employee.to_param}, valid_session
      assigns(:directory_employee).should eq(employee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Directory::Employee" do
        expect {
          post :create, {:directory_employee => valid_attributes}, valid_session
        }.to change(Directory::Employee, :count).by(1)
      end

      it "assigns a newly created directory_employee as @directory_employee" do
        post :create, {:directory_employee => valid_attributes}, valid_session
        assigns(:directory_employee).should be_a(Directory::Employee)
        assigns(:directory_employee).should be_persisted
      end

      it "redirects to the created directory_employee" do
        post :create, {:directory_employee => valid_attributes}, valid_session
        response.should redirect_to(Directory::Employee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directory_employee as @directory_employee" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::Employee.any_instance.stub(:save).and_return(false)
        post :create, {:directory_employee => {  }}, valid_session
        assigns(:directory_employee).should be_a_new(Directory::Employee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::Employee.any_instance.stub(:save).and_return(false)
        post :create, {:directory_employee => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directory_employee" do
        employee = Directory::Employee.create! valid_attributes
        # Assuming there are no other directory_employees in the database, this
        # specifies that the Directory::Employee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Directory::Employee.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => employee.to_param, :directory_employee => { "these" => "params" }}, valid_session
      end

      it "assigns the requested directory_employee as @directory_employee" do
        employee = Directory::Employee.create! valid_attributes
        put :update, {:id => employee.to_param, :directory_employee => valid_attributes}, valid_session
        assigns(:directory_employee).should eq(employee)
      end

      it "redirects to the directory_employee" do
        employee = Directory::Employee.create! valid_attributes
        put :update, {:id => employee.to_param, :directory_employee => valid_attributes}, valid_session
        response.should redirect_to(employee)
      end
    end

    describe "with invalid params" do
      it "assigns the directory_employee as @directory_employee" do
        employee = Directory::Employee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::Employee.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee.to_param, :directory_employee => {  }}, valid_session
        assigns(:directory_employee).should eq(employee)
      end

      it "re-renders the 'edit' template" do
        employee = Directory::Employee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directory::Employee.any_instance.stub(:save).and_return(false)
        put :update, {:id => employee.to_param, :directory_employee => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directory_employee" do
      employee = Directory::Employee.create! valid_attributes
      expect {
        delete :destroy, {:id => employee.to_param}, valid_session
      }.to change(Directory::Employee, :count).by(-1)
    end

    it "redirects to the directory_employees list" do
      employee = Directory::Employee.create! valid_attributes
      delete :destroy, {:id => employee.to_param}, valid_session
      response.should redirect_to(directory_employees_url)
    end
  end

end
